libraryApp/config/routes.rb
Rails.application.routes.draw do

root 'authors#index'
 resources :authors do
  resources :books, shallow: true
  end

end


#          Prefix Verb   URI Pattern                             Controller#Action
#            root GET    /                                       authors#index
#    author_books GET    /authors/:author_id/books(.:format)     books#index
#                 POST   /authors/:author_id/books(.:format)     books#create
# new_author_book GET    /authors/:author_id/books/new(.:format) books#new
#       edit_book GET    /books/:id/edit(.:format)               books#edit
#            book GET    /books/:id(.:format)                    books#show
#                 PATCH  /books/:id(.:format)                    books#update
#                 PUT    /books/:id(.:format)                    books#update
#                 DELETE /books/:id(.:format)                    books#destroy
#         authors GET    /authors(.:format)                      authors#index
#                 POST   /authors(.:format)                      authors#create
#      new_author GET    /authors/new(.:format)                  authors#new
#     edit_author GET    /authors/:id/edit(.:format)             authors#edit
#          author GET    /authors/:id(.:format)                  authors#show
#                 PATCH  /authors/:id(.:format)                  authors#update
#                 PUT    /authors/:id(.:format)                  authors#update
#                 DELETE /authors/:id(.:format)                  authors#destroy

libraryApp/app/models/author.rb
class Author < ActiveRecord::Base
	has_many :books, dependent: :destroy
	validates :first_name, presence: true
	validates :last_name, presence: true
end

libraryApp/app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to :author
	validates :title, presence: true
end

libraryApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

libraryApp/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

	before_action :find_author, only: [:show, :edit, :update, :destroy]
  def index
  	@authors = Author.all
  end

  def new
  	@author = Author.new
  end

  def create
  	@author = Author.new(author_params)
  	if @author.save
      flash[:success] = "Author Added"
  		redirect_to authors_path
  	else
  		render :new
  	end

  end

  def show
  end

  def edit
  end

  def update
  	if @author.update author_params
  		redirect_to author_path(@author), notice: "Author Updated"
  	else
  		render :edit
  	end
  end

  def destroy
  	if @author.destroy
  		redirect_to authors_path, alert: "Author Deleted"
  	else
  		render :show
  	end
  end

  private 
  	def author_params
  		params.require(:author).permit(:first_name, :last_name, :age)
  	end

  	def find_author
  		@author = Author.find_by_id params[:id]
  	end
end

libraryApp/app/controllers/books_controller.rb
class BooksController < ApplicationController

	before_action :find_author, only: [:index, :new, :create]
	before_action :find_book, only: [:show, :edit, :update, :destroy]

  def index
  end

  def new
  	@book = Book.new
  end

  def create
  	@book = @author.books.new(book_params)
  	if @book.save
  		flash[:success] = "Book Added"
  		redirect_to author_books_path(@author)
  	else
  		render :new
  	end
  end

  def show
  end

  def edit
  end

  def update
  	if @book.update book_params
  		redirect_to book_path(@book), notice: "Book Updated"
  	else
  		render :edit
  	end
  end

  def destroy
  	if @book.destroy
  		redirect_to author_books_path(@books.author)
  	else
  		render :show
  	end
  end

  private
  	def book_params
  		params.require(:book).permit(:title, :description)
  	end

	  def find_author
	  	@author = Author.find_by_id params[:author_id]
	  end

	  def find_book
	  	@book = Book.find_by_id params[:id]
	  end

end

libraryApp/app/helpers/application_helper.rb
module ApplicationHelper
end

libraryApp/app/helpers/authors_helper.rb
module AuthorsHelper
end

libraryApp/app/helpers/books_helper.rb
module BooksHelper
end

libraryApp/app/views/authors/_form.html.erb
<%if @author.errors.any? %>
	<% @author.errors.full_messages.each do |error| %>
		<p style="color:red"><%= error %></p>
	<%end %>
<% end %>

<%= form_for @author do |f| %>
		<%= f.label "First Name" %>
		<%= f.text_field :first_name, autofocus: true %><br/>
    <%= f.label "Last Name" %>
    <%= f.text_field :last_name%><br />
    <%= f.label "Age" %>
		<%= f.text_field :age %><br/>
    <%= f.submit%>
<% end %>

libraryApp/app/views/authors/edit.html.erb
<h1>Edit Information</h1>
<%= render "form" %>

libraryApp/app/views/authors/index.html.erb
<h1>Authors</h1>
<% @authors.each do |author| %>
	<div><%= author.first_name %> <%= author.last_name %>, <%= author.age %> years old.</div>
	<%= link_to "More About #{author.last_name}", author_path(author) %>
<% end %>

libraryApp/app/views/authors/new.html.erb
<h1>Add an Author</h1>
<%= render 'form' %>

libraryApp/app/views/authors/show.html.erb
<h1><%= @author.first_name %> <%= @author.last_name %></h1>
<%= @author.last_name %> is <%= @author.age %> years old.
<%= link_to "Books by #{@author.first_name} #{@author.last_name}", author_books_path(@author) %>

libraryApp/app/views/books/_form.html.erb
<%if @book.errors.any? %>
<% @book.errors.full_messages.each do |error| %>
<p style="color:red"><%= error %></p>
<% end %>
<% end %>

<%= form_for [@author,@book] do |f| %>
		<%= f.label "Title" %>
		<%= f.text_field :title, autofocus: true %><br/>
    <%= f.label "Description" %>
    <%= f.text_field :description%><br />
    <%= f.submit%>
<% end %>

libraryApp/app/views/books/edit.html.erb
<h1>Edit Book</h1>
<%= render "form" %>

libraryApp/app/views/books/index.html.erb
<h1>Books by <%= @author.first_name %> <%= @author.last_name %></h1>
<%= link_to "Add Book", new_author_book_path(@author) %>

<% @author.books.each do |book| %>
	<h3><%= book.title %></h3>
	<p><%= book.description %></p>
<%= link_to "More Information about #{book.title}", book_path(book) %>
<%= link_to "Edit #{book.title}", edit_book_path(book) %>

<% end %>

libraryApp/app/views/books/new.html.erb
<h1>Add a Book</h1>
<%= render "form" %>

libraryApp/app/views/books/show.html.erb
<h1><%= @book.title %></h1>
<p><%= @book.description %></p>
<%= link_to "Edit Book", edit_book_path(@book) %>

libraryApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LibraryApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>


<body class="container">
<% flash.each do |key, value| %>
  <% if key == "notice" %>
    <%= content_tag :div, value, class: "text-center alert alert-warning" %>
  <% elsif key == "alert" %>
    <%= content_tag :div, value, class: "text-center alert alert-danger" %>
  <% else %>
    <%= content_tag :div, value, class: "text-center alert alert-success" %>
  <% end %>
<% end %>

<ul class= "nav nav-tabs nav-justified">
	<li><%= link_to "HOME", root_path %></li>
	<li><%= link_to "ADD AUTHOR", new_author_path %></li>
</ul>
<%= yield %>

</body>
</html>